### ISSUE TITLE
Using a `sector_identifier_uri` instead of the `redirect_uri`

### ISSUE THREAD

**Issue by shaardie** [IdentityPython/pyop#49]
According to the [OIDC Documentation](https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg)

> If the Client has not provided a value for sector_identifier_uri in [Dynamic Client Registration](https://openid.net/specs/openid-connect-core-1_0.html#OpenID.Registration) [OpenID.Registration], the Sector Identifier used for pairwise identifier calculation is the host component of the registered redirect_uri. If there are multiple hostnames in the registered redirect_uris, the Client MUST register a sector_identifier_uri.

But as far as I can see it, pyop is always using the `redirect_uri` from the authenticate request, even if multiple redirect_uris are defined, see [here](https://github.com/IdentityPython/pyop/blob/837045e/src/pyop/provider.py#L243)

```python
    def _create_subject_identifier(self, user_id, client_id, redirect_uri):
        # type (str, str, str) -> str
        """
        Creates a subject identifier for the specified client and user
        see <a href="http://openid.net/specs/openid-connect-core-1_0.html#Terminology">
        "OpenID Connect Core 1.0", Section 1.2</a>.
        :param user_id: local user identifier
        :param client_id: which client to generate a subject identifier for
        :param redirect_uri: the clients' redirect_uri
        :return: a subject identifier for the user intended for client who made the authentication request
        """
        supported_subject_types = self.configuration_information['subject_types_supported'][0]
        subject_type = self.clients[client_id].get('subject_type', supported_subject_types)
        sector_identifier = urlparse(redirect_uri).netloc
        return self.authz_state.get_subject_identifier(subject_type, user_id, sector_identifier)
```

This can lead to problems, because different redirect_uris or changing the redirect_uri leads to another sub, which can result in problem in the systems using them as identifier (e.g. harbor).

**Comment by shaardie** [comment]
Maybe a simple

```python
sector_identifier = self.clients[client_id].get("sector_identifier_uri", urlparse(redirect_uri).netloc)
```

or something similar would to the trick. If you want, I can create a PR.

**Comment by vladimir-mencl-eresearch** [comment]
That is a very reasonable and well justified approach - can you please send in a PR?

**Comment by c00kiemon5ter** [comment]
I agree with this, but would suggest to keep `urlparse(redirect_uri).netloc` as the default value.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @c00kiemon5ter , the code proposed by @shaardie would correctly implement the specification.  And for clients that do not set `sector_identifier`, it would produce the same values as current behaviour.

What do you mean by proposing to:
>  keep `urlparse(redirect_uri).netloc` as the default value.
?

Cheers,
Vlad

**Comment by c00kiemon5ter** [comment]
duh, yes of course; I didn't notice. That is great 👍

**Comment by shaardie** [comment]
I created a PR for this as we discussed above with the only difference to use also `netloc` of the `subject_identifier_uri`, because it according to the documentation:

> When a sector_identifier_uri is provided, the host component of that URL is used as the Sector Identifier for the pairwise identifier calculation. The value of the sector_identifier_uri MUST be a URL...

**Comment by c00kiemon5ter** [comment]
thank you @shaardie
